<?php
return [
    'Filter_Type_Tag' => 0,
    'Filter_Type_Country' => 1,
    'Filter_Type_University' => 2,
    'Filter_Type_Course' => 3,
    'Filter_Type_Language' => 4,
    'Privacy_Public' => 0,
    'Privacy_Private' => 1,
    'Privacy_Followers' => 2,
    'User_Type_Student' => 1,
    'User_Type_Faculty' => 2,
    'User_Type_Guest' => 3,
    'User_Type_Admin' => 4,
    'User_Type_University' => 5,
    'FollowPending' => 1,
    'FollowApproved' => 2,
    'FollowRejected' => 3,
    'User_Status_Active' => 1,
    'User_Status_Suspend' => 2,
    'User_Status_Deactivate' => 3,
    'User_Status_Terminate' => 4,
    'Notification_Type_Send_Following_Request' => 1,
    'Notification_Type_Accept_Following_Request' => 2,
    'Notification_Type_Comment_On_Question' => 3,
    'Notification_Type_Like_On_Question' => 4,
    'Notification_Type_Following_Posted_Question' => 5,
    'Notification_Type_Following_Posted_Library' => 6,
    'Notification_Type_Comment_On_Library' => 7,
    'Notification_Type_Question_Post_In_Category' => 8,
    'Notification_Type_Library_Post_In_Category' => 9,
    'Notification_Type_Following_Posted_Event' => 10,
    'Notification_Type_Event_Post_In_Category' => 11,
    
];
?>
